FROM ubuntu:xenial-20170619

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y ca-certificates

#ADD https://get.aquasec.com/microscanner .
#RUN chmod +x microscanner
#RUN ./microscanner

CMD ["/bin/bash"]
