apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app3
  namespace: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
        env: demo
    spec:
      containers:
        - name: app3
          image: nginxdemos/hello:plain-text
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
