---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elx:podsecuritypolicy:privileged
rules:
  - apiGroups:
      - policy
    resourceNames:
      - elx.privileged
    resources:
      - podsecuritypolicies
    verbs:
      - use
