# Bind the ClusterRole to the desired set of service accounts.
# Policies should typically be bound to service accounts in a namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app2:podsecuritypolicy:app2
  namespace: app2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app2:podsecuritypolicy:noroot-nopriv
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
