apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app2
  namespace: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: nginxdemos/hello:plain-text
#        image: nginxinc/nginx-unprivileged
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
