kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app2:podsecuritypolicy:noroot-nopriv
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - app2.noroot-nopriv
  verbs:
  - use
